# Generated by Django 4.0.1 on 2022-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweetlike'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tweetlike',
            constraint=models.UniqueConstraint(fields=('tweet', 'liked_by'), name='like_unique'),
        ),
    ]
