# Generated by Django 4.0.1 on 2022-04-21 17:36

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_email_tweet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='image',
            field=models.ImageField(upload_to=user.models.user_directory_path),
        ),
    ]
